/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jesgoo.wharf.thrift.wharfdata;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EventType implements org.apache.thrift.TEnum {
  LOG(1),
  SIGN2(2),
  SIGN3(3),
  SIGN4(4);

  private final int value;

  private EventType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EventType findByValue(int value) { 
    switch (value) {
      case 1:
        return LOG;
      case 2:
        return SIGN2;
      case 3:
        return SIGN3;
      case 4:
        return SIGN4;
      default:
        return null;
    }
  }
}
